// <auto-generated />
namespace MantenimientoCasa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DireccionRequerida : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DireccionRequerida));
        
        string IMigrationMetadata.Id
        {
            get { return "202105010034303_DireccionRequerida"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
